# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-12 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pis_product', '0002_purchasedproduct_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchasedproduct',
            name='manual_discount',
        ),
        migrations.AlterField(
            model_name='purchasedproduct',
            name='discount_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=65, null=True),
        ),
        migrations.AlterField(
            model_name='purchasedproduct',
            name='purchase_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=65, null=True),
        ),
        migrations.AlterField(
            model_name='purchasedproduct',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=65, null=True),
        ),
    ]
