# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-04 12:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pis_retailer', '0002_retailer_logo'),
        ('pis_product', '0003_auto_20180412_1827'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item_name', models.CharField(blank=True, max_length=100, null=True)),
                ('quantity', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=65, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=65, null=True)),
                ('retailer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retailer_extra_items', to='pis_retailer.Retailer')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
