# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-07 09:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pis_product', '0006_purchasedproduct_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimedProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claimed_items', models.IntegerField(default=1, verbose_name='No. of Claimed Items')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claimed_product', to='pis_product.Product')),
            ],
        ),
    ]
