# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-11-15 08:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pis_product', '0008_auto_20180608_2226'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockIn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(blank=True, max_length=100, null=True)),
                ('price_per_item', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=65, null=True)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=65, null=True)),
                ('dated_order', models.DateField(blank=True, null=True)),
                ('stock_expiry', models.DateField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stockin_product', to='pis_product.Product')),
            ],
        ),
        migrations.CreateModel(
            name='StockOut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_out_quantity', models.CharField(blank=True, max_length=100, null=True)),
                ('dated', models.DateField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stockout_product', to='pis_product.Product')),
            ],
        ),
    ]
