# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-01-17 07:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pis_product', '0009_stockin_stockout'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='bar_code',
            field=models.CharField(blank=True, max_length=13, null=True, unique=True),
        ),
    ]
