# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-06-26 12:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pis_product', '0012_auto_20190122_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockin',
            name='buying_price_item',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Buying Price for a Single Item', max_digits=65, null=True),
        ),
        migrations.AddField(
            model_name='stockin',
            name='total_buying_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=65, null=True),
        ),
        migrations.AddField(
            model_name='stockout',
            name='buying_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=65, null=True),
        ),
        migrations.AddField(
            model_name='stockout',
            name='selling_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=65, null=True),
        ),
        migrations.AlterField(
            model_name='stockin',
            name='price_per_item',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Selling Price for a Single Item', max_digits=65, null=True),
        ),
    ]
