# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-06-26 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pis_product', '0014_auto_20190626_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
