# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-08-09 06:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pis_product', '0016_auto_20190809_0544'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockout',
            name='purchased_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='out_purchased', to='pis_product.PurchasedProduct'),
        ),
    ]
