# Generated by Django 5.1.7 on 2026-04-14 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pis_product', '0018_alter_claimedproduct_id_alter_extraitems_id_and_more'),
        ('pis_retailer', '0007_alter_retailer_id_alter_retaileruser_id'),
        ('pis_sales', '0011_alter_saleshistory_extra_items_alter_saleshistory_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='claimedproduct',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='extraitems',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Extra items'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='productdetail',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='purchasedproduct',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='stockin',
            options={'ordering': ['-dated_order']},
        ),
        migrations.AlterModelOptions(
            name='stockout',
            options={'ordering': ['-dated']},
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='stockout',
            name='dated',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name='stockout',
            index=models.Index(fields=['product', 'dated'], name='stockout_product_dated_idx'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('retailer', 'name'), name='unique_product_per_retailer'),
        ),
    ]
