# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-27 07:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pis_retailer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('receipt_no', models.CharField(max_length=20)),
                ('customer_name', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('product_details', models.TextField(blank=True, help_text='Quantity and Product name would save in JSON format', max_length=512, null=True)),
                ('retail_amount', models.DecimalField(decimal_places=2, default=0, max_digits=65)),
                ('consumer_amount', models.DecimalField(decimal_places=2, default=0, max_digits=65)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=65)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=65)),
                ('profit', models.DecimalField(decimal_places=2, default=0, max_digits=65)),
                ('retailer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retailer_sales', to='pis_retailer.Retailer')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
