# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-12 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pis_product', '0002_purchasedproduct_quantity'),
        ('pis_sales', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saleshistory',
            name='consumer_amount',
        ),
        migrations.RemoveField(
            model_name='saleshistory',
            name='profit',
        ),
        migrations.RemoveField(
            model_name='saleshistory',
            name='retail_amount',
        ),
        migrations.RemoveField(
            model_name='saleshistory',
            name='total',
        ),
        migrations.AddField(
            model_name='saleshistory',
            name='grand_total',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=65, null=True),
        ),
        migrations.AddField(
            model_name='saleshistory',
            name='purchased_items',
            field=models.ManyToManyField(blank=True, max_length=100, null=True, to='pis_product.PurchasedProduct'),
        ),
        migrations.AddField(
            model_name='saleshistory',
            name='shipping',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=65, null=True),
        ),
        migrations.AddField(
            model_name='saleshistory',
            name='sub_total',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=65, null=True),
        ),
        migrations.AddField(
            model_name='saleshistory',
            name='total_quantity',
            field=models.CharField(blank=True, default=1, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='saleshistory',
            name='receipt_no',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
