# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-12 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pis_sales', '0003_auto_20180412_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleshistory',
            name='remaining_payment',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=65, null=True),
        ),
    ]
