# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-27 12:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pis_retailer', '0002_retailer_logo'),
        ('pis_sales', '0004_saleshistory_remaining_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200)),
                ('customer_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('retailer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pis_retailer.Retailer')),
            ],
        ),
    ]
