# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-27 12:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pis_sales', '0005_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saleshistory',
            name='customer_name',
        ),
        migrations.RemoveField(
            model_name='saleshistory',
            name='customer_phone',
        ),
        migrations.AddField(
            model_name='saleshistory',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_sales', to='pis_sales.Customer'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='retailer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retailer_customer', to='pis_retailer.Retailer'),
        ),
    ]
