# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-04 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pis_product', '0004_extraitems'),
        ('pis_sales', '0006_auto_20180427_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleshistory',
            name='extra_items',
            field=models.ManyToManyField(blank=True, max_length=200, null=True, to='pis_product.ExtraItems'),
        ),
    ]
