# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-09 13:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pis_sales', '0007_auto_20180504_1940'),
        ('pis_sales', '0007_saleshistory_extra_items'),
    ]

    operations = [
    ]
