# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-06-22 07:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pis_sales', '0009_saleshistory_paid_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleshistory',
            name='cash_payment',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=65, null=True),
        ),
        migrations.AddField(
            model_name='saleshistory',
            name='returned_payment',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=65, null=True),
        ),
    ]
