# Generated by Django 5.1.7 on 2026-04-14 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pis_product', '0018_alter_claimedproduct_id_alter_extraitems_id_and_more'),
        ('pis_sales', '0010_auto_20190622_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleshistory',
            name='extra_items',
            field=models.ManyToManyField(blank=True, to='pis_product.extraitems'),
        ),
        migrations.AlterField(
            model_name='saleshistory',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='saleshistory',
            name='purchased_items',
            field=models.ManyToManyField(blank=True, to='pis_product.purchasedproduct'),
        ),
        migrations.AlterField(
            model_name='saleshistory',
            name='total_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=65, null=True),
        ),
    ]
