# Generated by Django 5.1.7 on 2026-04-14 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pis_com', '0014_alter_customer_options_alter_feedback_options'),
        ('pis_product', '0019_alter_claimedproduct_options_and_more'),
        ('pis_retailer', '0007_alter_retailer_id_alter_retaileruser_id'),
        ('pis_sales', '0011_alter_saleshistory_extra_items_alter_saleshistory_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='saleshistory',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Sales histories'},
        ),
        migrations.AlterField(
            model_name='saleshistory',
            name='receipt_no',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='saleshistory',
            index=models.Index(fields=['retailer', 'created_at'], name='sales_retailer_created_idx'),
        ),
    ]
