# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-19 11:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pis_retailer', '0003_retaileruser_role_type'),
        ('pis_ledger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledger',
            name='retailer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='retailer_ledger', to='pis_retailer.Retailer'),
        ),
        migrations.AddField(
            model_name='paymentledger',
            name='retailer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='retailer_ledger_payment', to='pis_retailer.Retailer'),
        ),
    ]
