# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-08 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pis_ledger', '0002_auto_20180519_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentledger',
            name='description',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ledger',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
