# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-12 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pis_ledger', '0003_auto_20180608_2252'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentledger',
            name='payment_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
