# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-02-02 11:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pis_ledger', '0005_ledger_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledger',
            name='person',
            field=models.CharField(blank=True, default='customer', max_length=200, null=True),
        ),
    ]
