# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-08-07 08:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pis_ledger', '0006_auto_20190202_1659'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentledger',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='paymentledger',
            name='retailer',
        ),
        migrations.AddField(
            model_name='ledger',
            name='payment',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=65, null=True),
        ),
        migrations.AddField(
            model_name='ledger',
            name='payment_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ledger',
            name='description',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='PaymentLedger',
        ),
    ]
