# Generated by Django 5.1.7 on 2026-04-14 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pis_ledger', '0009_ledger_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledger',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
