# Generated by Django 5.1.7 on 2026-04-14 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pis_ledger', '0010_alter_ledger_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ledger',
            options={'ordering': ['-dated']},
        ),
    ]
