# Generated by Django 5.1.7 on 2026-04-14 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pis_expense', '0002_alter_extraexpense_amount_alter_extraexpense_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='extraexpense',
            options={'ordering': ['-date']},
        ),
    ]
