# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-04 11:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pis_retailer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='retailer',
            name='logo',
            field=models.ImageField(blank=True, max_length=1024, null=True, upload_to='images/retailer/logo/'),
        ),
    ]
