# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-30 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pis_retailer', '0002_retailer_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='retaileruser',
            name='role_type',
            field=models.CharField(choices=[('owner', 'Owner'), ('data_entry_user', 'Data Entry User'), ('salesman', 'Salesman'), ('account_viewer', 'Account Viewer')], default='owner', max_length=100),
        ),
    ]
