# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-23 10:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pis_retailer', '0003_retaileruser_role_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retaileruser',
            name='role_type',
            field=models.CharField(choices=[('owner', 'Owner'), ('data_entry_user', 'Data Entry User'), ('salesman', 'Salesman'), ('account_viewer', 'Account Viewer'), ('ledger_viewer', 'Ledger Viewer')], default='owner', max_length=100),
        ),
    ]
