# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-02-08 09:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pis_retailer', '0004_auto_20180623_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='retailer',
            name='package',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='retailer',
            name='package_price',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
