# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-05-30 10:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pis_retailer', '0005_auto_20190208_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='retailer',
            name='package_expiry',
            field=models.DateField(blank=True, null=True),
        ),
    ]
