# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-04 11:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pis_com', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('owner', 'Owner'), ('data_entry_clerk', 'Data Entry Clerk'), ('editor', 'Editor')], default='owner', max_length=100),
        ),
    ]
