# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-04 14:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pis_com', '0003_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='retailer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retailer_customer', to='pis_retailer.Retailer'),
        ),
    ]
