# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-10 15:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pis_com', '0004_auto_20180504_1944'),
        ('pis_com', '0003_auto_20180510_1458'),
    ]

    operations = [
    ]
