# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-04 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pis_com', '0005_merge_20180510_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='shop',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
