# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-28 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pis_com', '0006_auto_20180604_2203'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('production', models.BooleanField(default=False)),
                ('demo', models.BooleanField(default=False)),
                ('local', models.BooleanField(default=False)),
            ],
        ),
    ]
