# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-02-02 11:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pis_com', '0007_adminconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='person_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
