# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-02-02 12:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pis_com', '0009_auto_20190202_1638'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='person_type',
            new_name='customer_type',
        ),
    ]
