# Generated by Django 5.1.7 on 2026-04-14 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pis_com', '0013_alter_adminconfiguration_id_alter_customer_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['customer_name']},
        ),
        migrations.AlterModelOptions(
            name='feedback',
            options={'ordering': ['-date']},
        ),
    ]
