# Generated by Django 5.1.7 on 2026-04-14 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pis_employees', '0002_alter_employee_id_alter_employeesalary_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['-date_of_joining']},
        ),
        migrations.AlterModelOptions(
            name='employeesalary',
            options={'ordering': ['-date'], 'verbose_name_plural': 'Employee salaries'},
        ),
    ]
