# Generated by Django 5.1.7 on 2026-04-14 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pis_supplier', '0004_alter_supplier_id_alter_supplierstatement_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supplier',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='supplierstatement',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='supplierstatement',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplier_statements', to='pis_supplier.supplier'),
        ),
    ]
